### ISSUE TITLE
Fix Text Overflow for Tasks

### ISSUE THREAD

**Issue by JourneyToTheWes** [Pug-Life-INFO-461/allowance-gamification-app#106]
![image](https://user-images.githubusercontent.com/15175754/40762005-3d5d0028-6453-11e8-81ee-d3269d2b5d75.png)

**Comment by JourneyToTheWes** [comment]
![image](https://user-images.githubusercontent.com/15175754/40762023-61ee755c-6453-11e8-885b-e7fbb39ae238.png)


Points also don't show up for long task points

**Comment by Kidusyohanes** [comment]
fixed.
