### ISSUE TITLE
Child Tasks - In Progress Issue

### ISSUE THREAD

**Issue by JourneyToTheWes** [Pug-Life-INFO-461/allowance-gamification-app#109]
On the Accept page for tasks, are users supposed to just stay on that page until they finish it? They cannot log out and go back to that task? Is there no way to leave that page? When I accepted the task and went back, the **Task is no longer available but stuck in the void**.

**Comment by Kidusyohanes** [comment]
Once the task is accepted the user is supposed to stay on that page until they completed that task or cancel out of it. For the part where the task is stuck in the void after accepting and going back to the Available page is not in the design.

**Comment by Kidusyohanes** [comment]
I have attacked the bottom nav on inProgress page. I have made the Task button to take users back to that inprogress mode rather than to the child-task page.
