### ISSUE TITLE
Edit task Positioning

### ISSUE THREAD

**Issue by JourneyToTheWes** [Pug-Life-INFO-461/allowance-gamification-app#116]
![image](https://user-images.githubusercontent.com/15175754/40829240-b7f523ee-6537-11e8-85ec-a6931882e8f0.png)
Icons are not aligned with text.. Also title is not scrollable. Should be smaller in height. Probably need to set the height so that no matter the length of the text, it'll be scrollable.

**Comment by Kidusyohanes** [comment]
fixed
