### ISSUE TITLE
After typing in text for Task title

### ISSUE THREAD

**Issue by JourneyToTheWes** [Pug-Life-INFO-461/allowance-gamification-app#122]
![image](https://user-images.githubusercontent.com/15175754/40869953-8fe126d0-65d9-11e8-9cc5-2316d9b2e071.png)

> Text is the expected size, font, and color, but after leaving that input field, the text looks like shown above.

**Comment by 5tigerjelly** [comment]
Issue un-reproducible 
![image](https://user-images.githubusercontent.com/15973528/40871844-8181cc74-65f8-11e8-825e-78bad3467747.png)
