### ISSUE TITLE
Child Task in Progress

### ISSUE THREAD

**Issue by JourneyToTheWes** [Pug-Life-INFO-461/allowance-gamification-app#123]
After the child accepts a task, they are brought to this page: 
![image](https://user-images.githubusercontent.com/15175754/40871644-40c5af06-65f4-11e8-8d97-9dc21a4f55fc.png)

After navigating to rewards tab, the user needs to be able to navigate through whatever means and get to the task tab and the same "in progress" page (image above) should still be displayed until they cancel or complete assignment. Even after logout, that task "in progress" page should show up for children.

Right now, when navigating elsewhere, the task goes to in progress for parents and the child can't complete it or cancel since that page disappears.

**Comment by 5tigerjelly** [comment]
done
