### ISSUE TITLE
Create Task - Note is optional so there should not be an alert message to prevent users from creating task when it is not entered

### ISSUE THREAD

**Issue by Jingwnpn** [Pug-Life-INFO-461/allowance-gamification-app#136]
<img width="389" alt="screen shot 2018-06-03 at 3 50 44 am" src="https://user-images.githubusercontent.com/22405025/40885748-530bc5fe-66e1-11e8-9f4b-58bdbcfb018e.png">

**Comment by Kidusyohanes** [comment]
fixed.

**Comment by Kidusyohanes** [comment]
fixed.
