### ISSUE TITLE
When go to Edit Task/Reward mode, it does not show original task/reward information.

### ISSUE THREAD

**Issue by Jingwnpn** [Pug-Life-INFO-461/allowance-gamification-app#140]
<img width="895" alt="screen shot 2018-06-03 at 4 12 11 am" src="https://user-images.githubusercontent.com/22405025/40885923-57b96da6-66e4-11e8-908e-64b4c8454b31.png">

<img width="906" alt="screen shot 2018-06-03 at 5 23 49 am" src="https://user-images.githubusercontent.com/22405025/40886521-53341a1a-66ee-11e8-982d-e664c24772dc.png">

**Comment by 5tigerjelly** [comment]
the fuck I fixed this 2 days ago

**Comment by 5tigerjelly** [comment]
![image](https://user-images.githubusercontent.com/15973528/40891911-438d89ac-6743-11e8-80af-01b3ada6faa7.png)
works
