### ISSUE TITLE
Edit Task/Reward should follow the same requirements as Create Task/Reward

### ISSUE THREAD

**Issue by Jingwnpn** [Pug-Life-INFO-461/allowance-gamification-app#141]
**Task/Reward Title**
1. Task/Reward title is maximum 10 words long
2. If the Task/Reward title is longer than 10 words, an error message will display to inform users about the mistake
3. Task/Reward Title field is mandatory

**Point Value**
1. This field only allows to enter numbers
2. There is no limitation to the number users can enter
3. Point Value field is mandatory

**Note**
1. There is no word limitation
2. Note field is optional

**Comment by JourneyToTheWes** [comment]
Finished the mandatory error handling for edit task/rewards. I think Kidus finished for create Task/Rewards. I won't edit so there is no conflict.
