### ISSUE TITLE
Parent View - In Tasks In-Progress and Completed tabs, and Rewards Claimed tab,  it should show Gravatar of the child who accepted and completed the task, and who claimed the reward

### ISSUE THREAD

**Issue by Jingwnpn** [Pug-Life-INFO-461/allowance-gamification-app#145]
Below are the required designs:

![23 parents - tasks view - in progress](https://user-images.githubusercontent.com/22405025/40886200-97b429ba-66e8-11e8-9434-b58c02d22005.png)
![24 parents - tasks view - completed](https://user-images.githubusercontent.com/22405025/40886202-99d4c1dc-66e8-11e8-95c0-372088fff89a.png)

![29 parents - rewards - claimed](https://user-images.githubusercontent.com/22405025/40886562-1a80aa48-66ef-11e8-936b-7d757d2ece7c.png)

**Comment by Kidusyohanes** [comment]
fixed.
