### ISSUE TITLE
Create Tasks/Rewards - Point Value fields should only allow number input, but it allows to enter letter 'e'

### ISSUE THREAD

**Issue by Jingwnpn** [Pug-Life-INFO-461/allowance-gamification-app#148]
<img width="391" alt="screen shot 2018-06-03 at 5 18 54 am" src="https://user-images.githubusercontent.com/22405025/40886489-a1f2c008-66ed-11e8-8fd3-fd7a4106928d.png">

**Comment by Kidusyohanes** [comment]
e is a mathematical number thus it technically valid for a user to put it but I am sure users might be confused about that.
