### ISSUE TITLE
Parent View In progress Task disappears to the side

### ISSUE THREAD

**Issue by PYParkx** [Pug-Life-INFO-461/allowance-gamification-app#154]
<img width="1113" alt="screen shot 2018-06-03 at 5 31 33 pm" src="https://user-images.githubusercontent.com/19401335/40893058-0e1459ca-6754-11e8-9d56-1b319df4bc03.png">
<img width="1259" alt="screen shot 2018-06-03 at 5 31 20 pm" src="https://user-images.githubusercontent.com/19401335/40893060-0fe5a6b4-6754-11e8-92a6-d265a914ee61.png">
Once you make a task, you see the in progress tab and you can see the task slide to the left off the screen. Sometimes it shows you a bit of the task but not always.
Task should be moved similar to the unclaimed.
Steps
1) Create Task
2) Task should appear in unclaimed
3) Select in progress
4) you will see that task disappears to the side.

**Comment by Kidusyohanes** [comment]
Use a chrome developer (inspect) tools with mobile view of iPhone 5/6/7 for the intended purpose of the app.
