### ISSUE TITLE
Create a Family - cannot easily click on "Family Name" input

### ISSUE THREAD

**Issue by Kyle-Simpson** [Pug-Life-INFO-461/allowance-gamification-app#157]
I just opened up the site, I went to create a family, and I was unable to click on the top input box unless I clicked in a very specific location (the location being just under the text).  With each of the other inputs, I was able to click on the placeholder text for that input and begin entering my response, but with the top I was unable to be so flexible when trying to enter information.

[minor]

Reproduction steps:
1. Arrive at homepage of website
2. Click "Create a family"
3. Click on the placeholder text of the first input (doesn't work)
4. Click on the placeholder text of the following two inputs (does work)

**Comment by 5tigerjelly** [comment]
Fixed by @JourneyToTheWes

**Comment by JourneyToTheWes** [comment]
The input "id" and label "for" did not match up (small typo). Clicking on that placeholder text for the first input should now work.
