### ISSUE TITLE
Profile SignUp - No indication email is already in use

### ISSUE THREAD

**Issue by alexiskoss** [Pug-Life-INFO-461/allowance-gamification-app#158]
As I opened the site, clicked on "Create Family" and then attempted to create my own profile, I was not alerted that  my email address was already in use. The text below the email address field says my email is valid, but fails to alert me that I'm unable to sign up with it (however, there is an error printed to the console).

[Minor]

Reproduction steps:
1. Go to website home page
2. Click on "Create Family"
3. Fill in family name, password, and password confirmation
4. Fill in name, password, password confirmation, and person type (parent or child), but put in an email that is already stored in Firebase.
5. Click "Create" to see that the page goes nowhere and doesn't show any error text, except for in the console.

**Comment by 5tigerjelly** [comment]
This bug was not reproducable, for it will alert the user if the email was taken, regardless, a toast have been added to notify user if that is to ever happen.

![image](https://user-images.githubusercontent.com/15973528/40952695-2918a9aa-6831-11e8-8b9a-e360e5cc7337.png)

**Comment by abegel** [comment]
@alexiskoss Can you reproduce the bug now?
