### ISSUE TITLE
Able To Complete Tasks Multiple Times

### ISSUE THREAD

**Issue by lisakoss** [Pug-Life-INFO-461/allowance-gamification-app#159]
Once a parent adds a task, a child can complete the task many times over to gain the same amount of points again, even though this task is considered to be "complete" and is not "available".

[MAJOR]

Reproduction steps:
1. Login as a parent user and create a task.
2. Set a task title, point value, and add a note to the task. Press save.
3. Log out of the parent user and log in as a child.
4. Click on the recently made task under the "Available" tab category and click "Accept".
5. Click "Complete" on the task.
6. Click on the "Rewards" tab in the bottom navigation.
7. Verify you earned points. 
8. Go back to the "Tasks" tab in the bottom navigation.
9. Click on the "Completed" tab category in the upper navigation.
10. Click on the recently completed task and click "Accept" again.
11. Click "Complete" on the task.
12. Then click on the "Rewards" tab in the bottom navigation.
13. Verify you earned the same amount of points **again**, which is incorrect.

**Comment by Kidusyohanes** [comment]
Thank you for pointing that out. I have released a new patch. Feel free to test it.
