### ISSUE TITLE
complete button is not working

### ISSUE THREAD

**Issue by juan3674-1532739** [Pug-Life-INFO-461/allowance-gamification-app#163]
I made the task for children, and I was able to upload it. Then I logged in as a child and try to complete the task but it won't let me click the complete button.
![screen shot 2018-06-03 at 9 03 34 pm](https://user-images.githubusercontent.com/25023460/40897751-bc3ea204-6771-11e8-9ff6-5b287bee299a.png)

**Comment by 5tigerjelly** [comment]
fixed by @Kidusyohanes
