### ISSUE TITLE
Clicking on icon for unmasking passwords does not allow me to see my password

### ISSUE THREAD

**Issue by vaneshsu99** [Pug-Life-INFO-461/allowance-gamification-app#165]
When I created an account, I clicked on the icon to unmask my password. The icon disappeared and the password stayed displayed as dots instead of the letters I typed in.

Before:

<img width="399" alt="screen shot 2018-06-03 at 9 42 43 pm" src="https://user-images.githubusercontent.com/26750673/40898586-344edcb4-6777-11e8-95ff-5f4f20831d43.png">

After:

<img width="400" alt="screen shot 2018-06-03 at 9 43 17 pm" src="https://user-images.githubusercontent.com/26750673/40898589-3909be18-6777-11e8-9fd6-537684926363.png">

**Comment by JourneyToTheWes** [comment]
Revealing password by the icon is not in requirements, the icon was originally just a stylistic touch. Viewing password now works though.
