### ISSUE TITLE
Bottom of parent tasks screen cut off / can't scroll down

### ISSUE THREAD

**Issue by mariechristinesmet** [Pug-Life-INFO-461/allowance-gamification-app#167]
Image #1 (full view): 
![image](https://user-images.githubusercontent.com/32251054/40899645-da56eaac-677c-11e8-91ce-a0eaafb756e2.png)

Image #2 (close up):
![image](https://user-images.githubusercontent.com/32251054/40899586-93754444-677c-11e8-8dc0-4e30341bc3d6.png)
After I sign up and enter in information, I'm directed to the parent tasks page (https://pug-life-55e2e.firebaseapp.com/parent-tasks.html). There are two icons at the bottom of the screen and there appears to be text under it but the text is cut off and I am unable to scroll down.

**Comment by Kidusyohanes** [comment]
To run Pug Life's application, please follow these instructions:
- Users must use google chrome browser,
- Users must use the 'incognito' mode for each user
- Users must open developer tools, and toggle the mobile view
- Select the iPhone 6,7,8 option.
