### ISSUE TITLE
Can't click on eye icon to view my password during sign up

### ISSUE THREAD

**Issue by JaneQuichocho** [Pug-Life-INFO-461/allowance-gamification-app#168]
Reproduction steps
1. Go to sign up
2. Type in password
3. Click on eye icon that appears to the right when you type in your password

I think I should be able to see my password but nothing happens and the icon disappears.

**Comment by 5tigerjelly** [comment]
Duplicate of #165

**Comment by JourneyToTheWes** [comment]
Revealing password by the icon is not in requirements, the icon was originally just a stylistic touch. Viewing password now works though.
