### ISSUE TITLE
Bypassing all login steps

### ISSUE THREAD

**Issue by johnwjlim** [Pug-Life-INFO-461/allowance-gamification-app#169]
I'm able to bypass all login steps. Not sure if this is supposed to happen. 

Reproduction steps:

1) Visit https://pug-life-55e2e.firebaseapp.com/child-tasks.html in a new private window.

**Comment by johnwjlim** [comment]
![image](https://user-images.githubusercontent.com/34074206/40900347-ffd22208-677f-11e8-8ec1-220804912b55.png)

**Comment by johnwjlim** [comment]
![image](https://user-images.githubusercontent.com/34074206/40900531-c924b6a2-6780-11e8-9784-9e0b825518f5.png)
so in this case, I'm adding stuff to a non existent family I think

**Comment by 5tigerjelly** [comment]
This is supposed to be a mobile app wrapped. 
We are exposing the url just so we can demo.
In the application user does not have access to the url tab
