### ISSUE TITLE
Bottom Navigation bar doesn't fit on the desktop screen and I can't scroll down to view it

### ISSUE THREAD

**Issue by JaneQuichocho** [Pug-Life-INFO-461/allowance-gamification-app#170]
On the main screen when I log in, the bottom navigation bar has the words cut off and I can't scroll down to see what it says. I am using a google chrome browser on a windows computer with a screen size of 1024 by 768.

**Comment by Kidusyohanes** [comment]
To run Pug Life's application, please follow these instructions:

Users must use google chrome browser,
Users must use the 'incognito' mode for each user
Users must open developer tools, and toggle the mobile view
Select the iPhone 6,7,8 option.
