### ISSUE TITLE
Create task asking for point value even after there is input

### ISSUE THREAD

**Issue by johnwjlim** [Pug-Life-INFO-461/allowance-gamification-app#171]
Reproduction steps: 

1) Open a create task window as a parent
2) enter "e12345" as point value
3) Click submit

![image](https://user-images.githubusercontent.com/34074206/40900753-f3dd365c-6781-11e8-9c85-4b087d5dd12d.png)

**Comment by 5tigerjelly** [comment]
Only numbers are allowed in the point value,
on the mobile phone, only the number pad will pop up to prevent this. 

For the sake of the demo, on the browser, this cannot be prevented
