### ISSUE TITLE
Can't change the email address in edit profile screen

### ISSUE THREAD

**Issue by JaneQuichocho** [Pug-Life-INFO-461/allowance-gamification-app#173]
When I try to change the email address, nothing happens and I get a console error. And the email address is still the same as the old one when I go back to the profile screen.

Reproduction steps:
1. Log in
2. Navigate to profile screen
3. Click on the pencil icon
4. Change the current email address
5. Click on "Save"

![console-error](https://user-images.githubusercontent.com/35388572/40900769-07d41f54-6782-11e8-8018-01cc520713ef.JPG)

**Comment by 5tigerjelly** [comment]
email change now works

**Comment by abegel** [comment]
I see the same problem now.
