### ISSUE TITLE
Can't change password

### ISSUE THREAD

**Issue by JaneQuichocho** [Pug-Life-INFO-461/allowance-gamification-app#174]
When I try to change the password, nothing happens and I get a console error.

![console-error-password](https://user-images.githubusercontent.com/35388572/40901008-1dfeb478-6783-11e8-84de-140706a68294.JPG)

Reproduction steps:
1. Log in
2. Navigate to change password screen from menu in top right corner
3. Type in old password in password field
4. Type in new password in new password and confirm new password fields
5. Click on Save

**Comment by 5tigerjelly** [comment]
fixed
