### ISSUE TITLE
Still says "Email is already taken" after changing email to one that is definitely not taken

### ISSUE THREAD

**Issue by jmatray** [Pug-Life-INFO-461/allowance-gamification-app#175]
Minor

Step 1.
Put in an email that is already taken (jmatray@uw.edu)

Step 2.
See notification that email is taken

Step 3.
Change email to aakjsfdlkah@kajhdsflkah.com

Step 4.
Still see notification that email is taken

**Comment by 5tigerjelly** [comment]
fixed
