### ISSUE TITLE
Email address and password labels overlap the input fields in login screen

### ISSUE THREAD

**Issue by JaneQuichocho** [Pug-Life-INFO-461/allowance-gamification-app#176]
If I click on "Login" from the main screen, the email address and password labels initially overlap the text fields. But they go back to their normal position above the text field when I click on the text field.

![overlapping-labels](https://user-images.githubusercontent.com/35388572/40901174-db7db4a4-6783-11e8-8e5a-f99918c7473b.JPG)

**Comment by 5tigerjelly** [comment]
This is due to auto-filling feature of chrome, we will remove auto fill ins.
Thanks!

**Comment by 5tigerjelly** [comment]
fixed
