### ISSUE TITLE
Cannot change profile name

### ISSUE THREAD

**Issue by johnwjlim** [Pug-Life-INFO-461/allowance-gamification-app#177]
Unable to change profile name.

Reproduction steps: 
1) Go to edit profile
2) Change profile name 
3) Press save

![image](https://user-images.githubusercontent.com/34074206/40901222-24b08688-6784-11e8-9f39-5be949beacb5.png)

**Comment by 5tigerjelly** [comment]
fixed

**Comment by abegel** [comment]
I now get the same bug when trying to change my account email address from the Profile page.
