### ISSUE TITLE
1+12 = 1pt?

### ISSUE THREAD

**Issue by harrybarng** [Pug-Life-INFO-461/allowance-gamification-app#181]
as a child, I claimed 12pt worth task and a task with 0000000000000000000....00001 pt. When I went to check the point, while the tasks are marked completed, the child only has 1 pt
![image](https://user-images.githubusercontent.com/37923379/40907579-28d1ef12-6799-11e8-8846-6bfc5266a379.png)
![image](https://user-images.githubusercontent.com/37923379/40907583-2c85881c-6799-11e8-82a8-c01d0bd2282d.png)

**Comment by 5tigerjelly** [comment]
Unfortunately, you miss read our step up guide. 
You must use a new incognito browser for each child.

I can see behind that you have a parent-task tab open meaning there is a collision in the session browser.

**Comment by harrybarng** [comment]
i did use incognito

**Comment by 5tigerjelly** [comment]
You didn't read my comment as well.
A different browser, please.
