### ISSUE TITLE
email overflow extends the website width over body:100%;

### ISSUE THREAD

**Issue by harrybarng** [Pug-Life-INFO-461/allowance-gamification-app#182]
I inputed a very long email address long enough to overflow the screen width. The text went over the body width. 
![screen shot 2018-06-04 at 12 07 05 pm](https://user-images.githubusercontent.com/37923379/40936343-e31de122-67ef-11e8-9f19-2c6923305501.png)

**Comment by 5tigerjelly** [comment]
fixed
