### ISSUE TITLE
Bottom navigation bar (tasks/rewards) overflows past the bottom of the screen

### ISSUE THREAD

**Issue by samsturtevant** [Pug-Life-INFO-461/allowance-gamification-app#183]
Using a 1280p x 703p Chrome window, the menu options overflow below the fold, as seen below:
<img width="1280" alt="screen shot 2018-06-04 at 3 50 15 pm" src="https://user-images.githubusercontent.com/22480372/40945728-ff00d902-680e-11e8-96d6-6b9a1290bec0.png">

Reproduction steps:
1. Open a Chrome window, dimensions: 1280px703p
2. Sign in using a new family, and use a child account to log in
3. On the dashboard, the navigation bar overflows past the bottom edge. Icons are visible but text is partially cut off

**Comment by 5tigerjelly** [comment]
Did not follow set up steps.
Must use iPhone 6,7,8
