### ISSUE TITLE
In Task Detail the Edit button overlaps with the bottom navigation

### ISSUE THREAD

**Issue by Jingwnpn** [Pug-Life-INFO-461/allowance-gamification-app#70]
<img width="352" alt="screen shot 2018-05-26 at 11 09 24 am" src="https://user-images.githubusercontent.com/22405025/40579102-44dbf2cc-60d5-11e8-8e34-840a100b5bc8.png">

**Comment by Kidusyohanes** [comment]
Just fixed.
